// This file is auto-generated by @hey-api/openapi-ts

export const AgentChatRequestSchema = {
    properties: {
        query: {
            type: 'string',
            title: 'Query'
        },
        current_lat: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Lat'
        },
        current_lon: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Lon'
        }
    },
    type: 'object',
    required: ['query'],
    title: 'AgentChatRequest'
} as const;

export const AgentChatResponseSchema = {
    properties: {
        answer: {
            type: 'string',
            title: 'Answer'
        },
        internal_actions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Internal Actions'
        }
    },
    type: 'object',
    required: ['answer', 'internal_actions'],
    title: 'AgentChatResponse'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_vision_add_virtual_closetSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_vision-add_virtual_closet'
} as const;

export const Body_vision_upload_and_scanSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_vision-upload_and_scan'
} as const;

export const ClosetItemResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        image_path: {
            type: 'string',
            title: 'Image Path'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'image_path', 'created_at'],
    title: 'ClosetItemResponse'
} as const;

export const ClusterItemSchema = {
    properties: {
        cluster_id: {
            type: 'integer',
            title: 'Cluster Id'
        },
        center: {
            additionalProperties: true,
            type: 'object',
            title: 'Center'
        },
        places: {
            items: {
                '$ref': '#/components/schemas/PlaceResponse'
            },
            type: 'array',
            title: 'Places'
        },
        stores: {
            items: {
                '$ref': '#/components/schemas/app__domains__spatial__schema__StoreResponse'
            },
            type: 'array',
            title: 'Stores'
        }
    },
    type: 'object',
    required: ['cluster_id', 'center', 'places', 'stores'],
    title: 'ClusterItem'
} as const;

export const ClusterRequestSchema = {
    properties: {
        place_ids: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Place Ids'
        }
    },
    type: 'object',
    required: ['place_ids'],
    title: 'ClusterRequest'
} as const;

export const ClusterResponseSchema = {
    properties: {
        clusters: {
            items: {
                '$ref': '#/components/schemas/ClusterItem'
            },
            type: 'array',
            title: 'Clusters'
        }
    },
    type: 'object',
    required: ['clusters'],
    title: 'ClusterResponse'
} as const;

export const ContextInfoSchema = {
    properties: {
        time_slot: {
            type: 'string',
            title: 'Time Slot',
            default: 'none'
        },
        time_description: {
            type: 'string',
            title: 'Time Description',
            default: ''
        },
        weather_condition: {
            type: 'string',
            title: 'Weather Condition',
            default: 'Unknown'
        },
        weather_reason: {
            type: 'string',
            title: 'Weather Reason',
            default: ''
        },
        hour_used: {
            type: 'integer',
            title: 'Hour Used',
            default: 12
        }
    },
    type: 'object',
    title: 'ContextInfo',
    description: 'Thông tin ngữ cảnh đã được áp dụng — để hiển thị trên UI.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LockRequestSchema = {
    properties: {
        product_id: {
            type: 'integer',
            title: 'Product Id'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity',
            default: 1
        }
    },
    type: 'object',
    required: ['product_id'],
    title: 'LockRequest'
} as const;

export const LockResponseItemSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        product_id: {
            type: 'integer',
            title: 'Product Id'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        ttl_seconds: {
            type: 'integer',
            title: 'Ttl Seconds'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['id', 'product_id', 'quantity', 'status', 'ttl_seconds', 'expires_at'],
    title: 'LockResponseItem'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MixMatchProductSchema = {
    properties: {
        product_id: {
            type: 'integer',
            title: 'Product Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price: {
            type: 'integer',
            title: 'Price'
        },
        original_price: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Original Price'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        match_score: {
            type: 'number',
            title: 'Match Score'
        },
        stock: {
            type: 'integer',
            title: 'Stock',
            default: 0
        },
        store_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Store Id'
        }
    },
    type: 'object',
    required: ['product_id', 'name', 'price', 'match_score'],
    title: 'MixMatchProduct'
} as const;

export const MixMatchResponseSchema = {
    properties: {
        closet_item_id: {
            type: 'integer',
            title: 'Closet Item Id'
        },
        matches: {
            items: {
                '$ref': '#/components/schemas/MixMatchProduct'
            },
            type: 'array',
            title: 'Matches'
        },
        total_matches: {
            type: 'integer',
            title: 'Total Matches'
        }
    },
    type: 'object',
    required: ['closet_item_id', 'matches', 'total_matches'],
    title: 'MixMatchResponse'
} as const;

export const NearbySearchResponseSchema = {
    properties: {
        user_location: {
            additionalProperties: true,
            type: 'object',
            title: 'User Location'
        },
        search_radius_meters: {
            type: 'integer',
            title: 'Search Radius Meters'
        },
        total_found: {
            type: 'integer',
            title: 'Total Found'
        },
        places: {
            items: {
                '$ref': '#/components/schemas/PlaceResponse'
            },
            type: 'array',
            title: 'Places'
        }
    },
    type: 'object',
    required: ['user_location', 'search_radius_meters', 'total_found', 'places'],
    title: 'NearbySearchResponse'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const O2OContextResponseSchema = {
    properties: {
        place_info: {
            '$ref': '#/components/schemas/PlaceResponse'
        },
        nearby_stores: {
            items: {
                '$ref': '#/components/schemas/StoreWithProductsResponse'
            },
            type: 'array',
            title: 'Nearby Stores'
        }
    },
    type: 'object',
    required: ['place_info', 'nearby_stores'],
    title: 'O2OContextResponse'
} as const;

export const OrderCreateSchema = {
    properties: {
        product_id: {
            type: 'integer',
            title: 'Product Id'
        },
        store_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Store Id'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity',
            default: 1
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        phone: {
            type: 'string',
            title: 'Phone'
        },
        address: {
            type: 'string',
            title: 'Address'
        }
    },
    type: 'object',
    required: ['product_id', 'full_name', 'phone', 'address'],
    title: 'OrderCreate'
} as const;

export const OrderResponseSchema = {
    properties: {
        order_id: {
            type: 'integer',
            title: 'Order Id'
        },
        order_code: {
            type: 'string',
            title: 'Order Code'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        total_amount: {
            type: 'integer',
            title: 'Total Amount'
        },
        product_name: {
            type: 'string',
            title: 'Product Name'
        },
        vietqr_url: {
            type: 'string',
            title: 'Vietqr Url'
        }
    },
    type: 'object',
    required: ['order_id', 'order_code', 'status', 'total_amount', 'product_name', 'vietqr_url'],
    title: 'OrderResponse'
} as const;

export const PlaceDetailWithAISchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        place_id: {
            type: 'string',
            title: 'Place Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        lat: {
            type: 'number',
            title: 'Lat'
        },
        lon: {
            type: 'number',
            title: 'Lon'
        },
        ai_story: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Story'
        }
    },
    type: 'object',
    required: ['id', 'place_id', 'name', 'lat', 'lon'],
    title: 'PlaceDetailWithAI'
} as const;

export const PlaceResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        place_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Place Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        lat: {
            type: 'number',
            title: 'Lat'
        },
        lon: {
            type: 'number',
            title: 'Lon'
        },
        distance_meters: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Distance Meters'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating'
        },
        review_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Review Count'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        match_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Match Score'
        }
    },
    type: 'object',
    required: ['id', 'name', 'lat', 'lon'],
    title: 'PlaceResponse'
} as const;

export const PlannerRequestSchema = {
    properties: {
        current_lat: {
            type: 'number',
            title: 'Current Lat',
            description: 'Vĩ độ hiện tại của khách'
        },
        current_lon: {
            type: 'number',
            title: 'Current Lon',
            description: 'Kinh độ hiện tại của khách'
        },
        radius: {
            type: 'integer',
            maximum: 50000,
            minimum: 500,
            title: 'Radius',
            description: 'Bán kính tìm kiếm (mét)',
            default: 2000
        },
        keywords: {
            type: 'string',
            title: 'Keywords',
            description: 'Từ khóa tìm kiếm (vd: cafe, lụa, nón lá)',
            default: ''
        },
        weights: {
            '$ref': '#/components/schemas/WeightConfig',
            default: {
                rating: 0.4,
                distance: 0.3,
                price: 0.3
            }
        },
        top_n: {
            type: 'integer',
            maximum: 10,
            minimum: 1,
            title: 'Top N',
            description: 'Số lượng điểm đến tối ưu',
            default: 5
        },
        local_hour: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 23,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Local Hour',
            description: 'Giờ địa phương của khách (0-23). Nếu không gửi, hệ thống tự xác định theo UTC+7.'
        },
        max_budget: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Budget',
            description: 'Ngân sách tối đa (VNĐ). Nếu không gửi, không giới hạn ngân sách.'
        }
    },
    type: 'object',
    required: ['current_lat', 'current_lon'],
    title: 'PlannerRequest',
    description: 'Input từ Frontend (Bước 1).'
} as const;

export const PlannerResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status',
            default: 'success'
        },
        optimized_route: {
            items: {
                '$ref': '#/components/schemas/StopInRoute'
            },
            type: 'array',
            title: 'Optimized Route'
        },
        metrics: {
            '$ref': '#/components/schemas/RouteMetrics'
        },
        route_geometry: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RouteGeometry'
                },
                {
                    type: 'null'
                }
            ]
        },
        weather: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/WeatherInfo'
                },
                {
                    type: 'null'
                }
            ]
        },
        context_applied: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ContextInfo'
                },
                {
                    type: 'null'
                }
            ]
        },
        total_candidates: {
            type: 'integer',
            title: 'Total Candidates',
            description: 'Tổng số ứng viên thô trước khi lọc',
            default: 0
        }
    },
    type: 'object',
    required: ['optimized_route', 'metrics'],
    title: 'PlannerResponse',
    description: 'Output hoàn chỉnh trả về Frontend (Bước 2-4 kết hợp).'
} as const;

export const ProductCompactResponseSchema = {
    properties: {
        product_id: {
            type: 'integer',
            title: 'Product Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        price: {
            type: 'number',
            title: 'Price'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        }
    },
    type: 'object',
    required: ['product_id', 'name', 'price'],
    title: 'ProductCompactResponse'
} as const;

export const ProductInRouteSchema = {
    properties: {
        product_id: {
            type: 'integer',
            title: 'Product Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        price: {
            type: 'number',
            title: 'Price'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        }
    },
    type: 'object',
    required: ['product_id', 'name', 'price'],
    title: 'ProductInRoute',
    description: 'Sản phẩm gắn vào mỗi điểm dừng trong lộ trình.'
} as const;

export const ProductResponseSchema = {
    properties: {
        product_id: {
            type: 'integer',
            title: 'Product Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        price: {
            type: 'number',
            title: 'Price'
        },
        original_price: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Original Price'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        stock: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stock',
            default: 0
        },
        store_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Store Id'
        }
    },
    type: 'object',
    required: ['product_id', 'name', 'price'],
    title: 'ProductResponse'
} as const;

export const ReviewCreateSchema = {
    properties: {
        author_name: {
            type: 'string',
            title: 'Author Name'
        },
        rating: {
            type: 'integer',
            title: 'Rating'
        },
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    type: 'object',
    required: ['author_name', 'rating', 'text'],
    title: 'ReviewCreate'
} as const;

export const ReviewResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        place_id: {
            type: 'string',
            title: 'Place Id'
        },
        author_name: {
            type: 'string',
            title: 'Author Name'
        },
        rating: {
            type: 'integer',
            title: 'Rating'
        },
        text: {
            type: 'string',
            title: 'Text'
        },
        time_posted: {
            type: 'string',
            title: 'Time Posted'
        }
    },
    type: 'object',
    required: ['id', 'place_id', 'author_name', 'rating', 'text', 'time_posted'],
    title: 'ReviewResponse'
} as const;

export const RouteGeometrySchema = {
    properties: {
        geojson: {
            additionalProperties: true,
            type: 'object',
            title: 'Geojson'
        },
        duration_minutes: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Minutes'
        }
    },
    type: 'object',
    required: ['geojson'],
    title: 'RouteGeometry',
    description: 'GeoJSON geometry từ OSRM Route API — LineString đường thực tế.'
} as const;

export const RouteMetricsSchema = {
    properties: {
        total_price: {
            type: 'number',
            title: 'Total Price'
        },
        total_distance_km: {
            type: 'number',
            title: 'Total Distance Km'
        },
        routing_fallback_used: {
            type: 'boolean',
            title: 'Routing Fallback Used'
        }
    },
    type: 'object',
    required: ['total_price', 'total_distance_km', 'routing_fallback_used'],
    title: 'RouteMetrics',
    description: 'Số liệu tổng hợp của lộ trình.'
} as const;

export const RoutePlanRequestSchema = {
    properties: {
        current_lat: {
            type: 'number',
            maximum: 90,
            minimum: -90,
            title: 'Current Lat'
        },
        current_lon: {
            type: 'number',
            maximum: 180,
            minimum: -180,
            title: 'Current Lon'
        },
        place_ids: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Place Ids'
        }
    },
    type: 'object',
    required: ['current_lat', 'current_lon', 'place_ids'],
    title: 'RoutePlanRequest'
} as const;

export const RoutePlanResponseSchema = {
    properties: {
        total_distance_meters: {
            type: 'number',
            title: 'Total Distance Meters'
        },
        waypoints: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Waypoints'
        },
        polyline: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Polyline'
        },
        optimized_order: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Optimized Order'
        },
        weather_context: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Weather Context'
        }
    },
    type: 'object',
    required: ['total_distance_meters', 'waypoints', 'optimized_order'],
    title: 'RoutePlanResponse'
} as const;

export const SearchResultSchema = {
    properties: {
        stores: {
            items: {
                '$ref': '#/components/schemas/app__domains__inventory__schema__StoreResponse'
            },
            type: 'array',
            title: 'Stores',
            default: []
        },
        products: {
            items: {
                '$ref': '#/components/schemas/ProductResponse'
            },
            type: 'array',
            title: 'Products',
            default: []
        }
    },
    type: 'object',
    title: 'SearchResult'
} as const;

export const StopInRouteSchema = {
    properties: {
        order: {
            type: 'integer',
            title: 'Order'
        },
        store_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Store Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        lat: {
            type: 'number',
            title: 'Lat'
        },
        lon: {
            type: 'number',
            title: 'Lon'
        },
        rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating'
        },
        distance_km: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Distance Km'
        },
        final_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Final Score'
        },
        products: {
            items: {
                '$ref': '#/components/schemas/ProductInRoute'
            },
            type: 'array',
            title: 'Products',
            default: []
        }
    },
    type: 'object',
    required: ['order', 'name', 'lat', 'lon'],
    title: 'StopInRoute',
    description: 'Một điểm dừng trong lộ trình tối ưu.'
} as const;

export const StoreWithProductsResponseSchema = {
    properties: {
        store_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Store Id'
        },
        place_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Place Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        lat: {
            type: 'number',
            title: 'Lat'
        },
        lon: {
            type: 'number',
            title: 'Lon'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating'
        },
        products: {
            items: {
                '$ref': '#/components/schemas/ProductCompactResponse'
            },
            type: 'array',
            title: 'Products'
        }
    },
    type: 'object',
    required: ['name', 'lat', 'lon', 'products'],
    title: 'StoreWithProductsResponse'
} as const;

export const TaskStatusSchema = {
    properties: {
        task_id: {
            type: 'string',
            title: 'Task Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        image_path: {
            type: 'string',
            title: 'Image Path'
        },
        detected_objects: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Detected Objects'
        },
        matched_product_ids: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Matched Product Ids'
        }
    },
    type: 'object',
    required: ['task_id', 'status', 'image_path'],
    title: 'TaskStatus'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VisionUploadResponseSchema = {
    properties: {
        task_id: {
            type: 'string',
            title: 'Task Id'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['task_id', 'message'],
    title: 'VisionUploadResponse'
} as const;

export const WeatherInfoSchema = {
    properties: {
        temperature: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Temperature'
        },
        condition: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Condition'
        },
        code: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code'
        }
    },
    type: 'object',
    title: 'WeatherInfo',
    description: 'Thông tin thời tiết tại vị trí xuất phát.'
} as const;

export const WeightConfigSchema = {
    properties: {
        rating: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Rating',
            description: 'Trọng số đánh giá sao',
            default: 0.4
        },
        distance: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Distance',
            description: 'Trọng số khoảng cách',
            default: 0.3
        },
        price: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Price',
            description: 'Trọng số giá cả',
            default: 0.3
        }
    },
    type: 'object',
    title: 'WeightConfig',
    description: 'Bộ trọng số cho thuật toán Ranking MCDM.'
} as const;

export const app__domains__inventory__schema__StoreResponseSchema = {
    properties: {
        store_id: {
            type: 'integer',
            title: 'Store Id'
        },
        place_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Place Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        lat: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lat'
        },
        lon: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lon'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating'
        }
    },
    type: 'object',
    required: ['store_id', 'name'],
    title: 'StoreResponse'
} as const;

export const app__domains__spatial__schema__StoreResponseSchema = {
    properties: {
        store_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Store Id'
        },
        place_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Place Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        lat: {
            type: 'number',
            title: 'Lat'
        },
        lon: {
            type: 'number',
            title: 'Lon'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating'
        }
    },
    type: 'object',
    required: ['name', 'lat', 'lon'],
    title: 'StoreResponse'
} as const;
