// This file is auto-generated by @hey-api/openapi-ts

<<<<<<< HEAD
=======
export type AgentChatRequest = {
    query: string;
    current_lat?: (number | null);
    current_lon?: (number | null);
};

export type AgentChatResponse = {
    answer: string;
    internal_actions: Array<(string)>;
};

export type app__domains__inventory__schema__StoreResponse = {
    store_id: number;
    place_id?: (string | null);
    name: string;
    category?: (string | null);
    address?: (string | null);
    lat?: (number | null);
    lon?: (number | null);
    phone?: (string | null);
    rating?: (number | null);
};

export type app__domains__spatial__schema__StoreResponse = {
    store_id?: (number | null);
    place_id?: (string | null);
    name: string;
    category?: (string | null);
    address?: (string | null);
    lat: number;
    lon: number;
    phone?: (string | null);
    rating?: (number | null);
};

>>>>>>> origin/main
export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

<<<<<<< HEAD
=======
export type Body_vision_add_virtual_closet = {
    file: (Blob | File);
};

export type Body_vision_upload_and_scan = {
    file: (Blob | File);
};

export type ClosetItemResponse = {
    id: number;
    user_id: number;
    image_path: string;
    created_at: string;
};

export type ClusterItem = {
    cluster_id: number;
    center: {
        [key: string]: unknown;
    };
    places: Array<PlaceResponse>;
    stores: Array<app__domains__spatial__schema__StoreResponse>;
};

export type ClusterRequest = {
    place_ids: Array<(number)>;
};

export type ClusterResponse = {
    clusters: Array<ClusterItem>;
};

/**
 * Thông tin ngữ cảnh đã được áp dụng — để hiển thị trên UI.
 */
export type ContextInfo = {
    time_slot?: string;
    time_description?: string;
    weather_condition?: string;
    weather_reason?: string;
    hour_used?: number;
};

>>>>>>> origin/main
export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

<<<<<<< HEAD
=======
export type LockRequest = {
    product_id: number;
    quantity?: number;
};

export type LockResponseItem = {
    id: number;
    product_id: number;
    quantity: number;
    status: string;
    ttl_seconds: number;
    expires_at: string;
};

>>>>>>> origin/main
export type Message = {
    message: string;
};

<<<<<<< HEAD
=======
export type MixMatchProduct = {
    product_id: number;
    name: string;
    description?: (string | null);
    price: number;
    original_price?: (number | null);
    image_url?: (string | null);
    match_score: number;
    stock?: number;
    store_id?: (number | null);
};

export type MixMatchResponse = {
    closet_item_id: number;
    matches: Array<MixMatchProduct>;
    total_matches: number;
};

export type NearbySearchResponse = {
    user_location: {
        [key: string]: unknown;
    };
    search_radius_meters: number;
    total_found: number;
    places: Array<PlaceResponse>;
};

>>>>>>> origin/main
export type NewPassword = {
    token: string;
    new_password: string;
};

<<<<<<< HEAD
export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
=======
export type O2OContextResponse = {
    place_info: PlaceResponse;
    nearby_stores: Array<StoreWithProductsResponse>;
};

export type OrderCreate = {
    product_id: number;
    store_id?: (number | null);
    quantity?: number;
    full_name: string;
    phone: string;
    address: string;
};

export type OrderResponse = {
    order_id: number;
    order_code: string;
    status: string;
    total_amount: number;
    product_name: string;
    vietqr_url: string;
};

export type PlaceDetailWithAI = {
    id: number;
    place_id: string;
    name: string;
    category?: (string | null);
    address?: (string | null);
    lat: number;
    lon: number;
    ai_story?: (string | null);
};

export type PlaceResponse = {
    id: number;
    place_id?: (string | null);
    name: string;
    category?: (string | null);
    address?: (string | null);
    lat: number;
    lon: number;
    distance_meters?: (number | null);
    phone?: (string | null);
    rating?: (number | null);
    review_count?: (number | null);
    image_url?: (string | null);
    match_score?: (number | null);
};

/**
 * Input từ Frontend (Bước 1).
 */
export type PlannerRequest = {
    /**
     * Vĩ độ hiện tại của khách
     */
    current_lat: number;
    /**
     * Kinh độ hiện tại của khách
     */
    current_lon: number;
    /**
     * Bán kính tìm kiếm (mét)
     */
    radius?: number;
    /**
     * Từ khóa tìm kiếm (vd: cafe, lụa, nón lá)
     */
    keywords?: string;
    weights?: WeightConfig;
    /**
     * Số lượng điểm đến tối ưu
     */
    top_n?: number;
    /**
     * Giờ địa phương của khách (0-23). Nếu không gửi, hệ thống tự xác định theo UTC+7.
     */
    local_hour?: (number | null);
    /**
     * Ngân sách tối đa (VNĐ). Nếu không gửi, không giới hạn ngân sách.
     */
    max_budget?: (number | null);
};

/**
 * Output hoàn chỉnh trả về Frontend (Bước 2-4 kết hợp).
 */
export type PlannerResponse = {
    status?: string;
    optimized_route: Array<StopInRoute>;
    metrics: RouteMetrics;
    route_geometry?: (RouteGeometry | null);
    weather?: (WeatherInfo | null);
    context_applied?: (ContextInfo | null);
    /**
     * Tổng số ứng viên thô trước khi lọc
     */
    total_candidates?: number;
};

export type ProductCompactResponse = {
    product_id: number;
    name: string;
    price: number;
    image_url?: (string | null);
};

/**
 * Sản phẩm gắn vào mỗi điểm dừng trong lộ trình.
 */
export type ProductInRoute = {
    product_id: number;
    name: string;
    price: number;
    image_url?: (string | null);
};

export type ProductResponse = {
    product_id: number;
    name: string;
    price: number;
    original_price?: (number | null);
    description?: (string | null);
    image_url?: (string | null);
    stock?: (number | null);
    store_id?: (number | null);
};

export type ReviewCreate = {
    author_name: string;
    rating: number;
    text: string;
};

export type ReviewResponse = {
    id: number;
    place_id: string;
    author_name: string;
    rating: number;
    text: string;
    time_posted: string;
};

/**
 * GeoJSON geometry từ OSRM Route API — LineString đường thực tế.
 */
export type RouteGeometry = {
    geojson: {
        [key: string]: unknown;
    };
    duration_minutes?: (number | null);
};

/**
 * Số liệu tổng hợp của lộ trình.
 */
export type RouteMetrics = {
    total_price: number;
    total_distance_km: number;
    routing_fallback_used: boolean;
};

export type RoutePlanRequest = {
    current_lat: number;
    current_lon: number;
    place_ids: Array<(number)>;
};

export type RoutePlanResponse = {
    total_distance_meters: number;
    waypoints: Array<{
        [key: string]: unknown;
    }>;
    polyline?: (string | {
    [key: string]: unknown;
} | null);
    optimized_order: Array<(number)>;
    weather_context?: ({
    [key: string]: unknown;
} | null);
};

export type SearchResult = {
    stores?: Array<app__domains__inventory__schema__StoreResponse>;
    products?: Array<ProductResponse>;
};

/**
 * Một điểm dừng trong lộ trình tối ưu.
 */
export type StopInRoute = {
    order: number;
    store_id?: (number | null);
    name: string;
    category?: (string | null);
    address?: (string | null);
    lat: number;
    lon: number;
    rating?: (number | null);
    distance_km?: (number | null);
    final_score?: (number | null);
    products?: Array<ProductInRoute>;
};

export type StoreWithProductsResponse = {
    store_id?: (number | null);
    place_id?: (string | null);
    name: string;
    category?: (string | null);
    address?: (string | null);
    lat: number;
    lon: number;
    phone?: (string | null);
    rating?: (number | null);
    products: Array<ProductCompactResponse>;
};

export type TaskStatus = {
    task_id: string;
    status: string;
    image_path: string;
    detected_objects?: ({
    [key: string]: unknown;
} | null);
    matched_product_ids?: (Array<(number)> | null);
>>>>>>> origin/main
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

<<<<<<< HEAD
=======
export type VisionUploadResponse = {
    task_id: string;
    message: string;
};

/**
 * Thông tin thời tiết tại vị trí xuất phát.
 */
export type WeatherInfo = {
    temperature?: (number | null);
    condition?: (string | null);
    code?: (number | null);
};

/**
 * Bộ trọng số cho thuật toán Ranking MCDM.
 */
export type WeightConfig = {
    /**
     * Trọng số đánh giá sao
     */
    rating?: number;
    /**
     * Trọng số khoảng cách
     */
    distance?: number;
    /**
     * Trọng số giá cả
     */
    price?: number;
};

export type AgentChatWithAgentEndpointData = {
    requestBody: AgentChatRequest;
};

export type AgentChatWithAgentEndpointResponse = (AgentChatResponse);

export type CultureSearchCulturePlacesData = {
    q: string;
};

export type CultureSearchCulturePlacesResponse = (Array<PlaceResponse>);

export type CultureGetAiStoryData = {
    id: number;
};

export type CultureGetAiStoryResponse = (PlaceDetailWithAI);

export type CultureAddReviewData = {
    id: number;
    requestBody: ReviewCreate;
};

export type CultureAddReviewResponse = (ReviewResponse);

export type CultureGetReviewsData = {
    id: number;
};

export type CultureGetReviewsResponse = (Array<ReviewResponse>);

export type InventoryGetStoresData = {
    placeId?: (string | null);
};

export type InventoryGetStoresResponse = (Array<app__domains__inventory__schema__StoreResponse>);

export type InventoryGetProductData = {
    id: number;
};

export type InventoryGetProductResponse = (ProductResponse);

export type InventoryGetStoreProductsData = {
    storeId: number;
};

export type InventoryGetStoreProductsResponse = (Array<ProductResponse>);

export type InventorySearchData = {
    q?: string;
};

export type InventorySearchResponse = (SearchResult);

export type InventoryCreateInventoryLockData = {
    requestBody: LockRequest;
};

export type InventoryCreateInventoryLockResponse = ({
    [key: string]: unknown;
});

export type InventoryGetMyLocksResponse = (Array<LockResponseItem>);

export type InventoryReleaseExpiredData = {
    xInternalSecret?: (string | null);
};

export type InventoryReleaseExpiredResponse = (unknown);

export type InventoryComparePricesData = {
    lat?: (number | null);
    lon?: (number | null);
    productId: number;
    storeId: number;
};

export type InventoryComparePricesResponse = (unknown);

export type InventoryCreateOrderData = {
    requestBody: OrderCreate;
};

export type InventoryCreateOrderResponse = (OrderResponse);

>>>>>>> origin/main
export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

<<<<<<< HEAD
=======
export type LoginLogoutResponse = (Message);

>>>>>>> origin/main
export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

<<<<<<< HEAD
export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);
=======
export type PlannerGenerateItineraryData = {
    requestBody: PlannerRequest;
};

export type PlannerGenerateItineraryResponse = (PlannerResponse);

export type SpatialSearchPlacesOmniData = {
    lat?: number;
    lon?: number;
    q: string;
};

export type SpatialSearchPlacesOmniResponse = (Array<PlaceResponse>);

export type SpatialFindNearbyPlacesData = {
    lat: number;
    lon: number;
    radius?: number;
};

export type SpatialFindNearbyPlacesResponse = (NearbySearchResponse);

export type SpatialClusterAndGroupStoresData = {
    requestBody: ClusterRequest;
};

export type SpatialClusterAndGroupStoresResponse = (ClusterResponse);

export type SpatialCreateOptimalRouteData = {
    requestBody: RoutePlanRequest;
};

export type SpatialCreateOptimalRouteResponse = (RoutePlanResponse);

export type SpatialGetPlaceO2oContextApiData = {
    placeId: string;
    radius?: number;
};

export type SpatialGetPlaceO2oContextApiResponse = (O2OContextResponse);
>>>>>>> origin/main

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

<<<<<<< HEAD
export type UtilsHealthCheckResponse = (boolean);
=======
export type UtilsHealthCheckResponse = (unknown);

export type UtilsGetTelemetryResponse = ({
    [key: string]: unknown;
});

export type VisionUploadAndScanData = {
    formData: Body_vision_upload_and_scan;
};

export type VisionUploadAndScanResponse = (VisionUploadResponse);

export type VisionCheckTaskStatusData = {
    taskId: string;
};

export type VisionCheckTaskStatusResponse = (TaskStatus);

export type VisionMyClosetResponse = (Array<ClosetItemResponse>);

export type VisionAddVirtualClosetData = {
    formData: Body_vision_add_virtual_closet;
};

export type VisionAddVirtualClosetResponse = (ClosetItemResponse);

export type VisionGetMixMatchData = {
    itemId: number;
};

export type VisionGetMixMatchResponse = (MixMatchResponse);
>>>>>>> origin/main
