"""sync_domain_schema_v2

Revision ID: 1945bf0afe56
Revises: fe56fa70289e
Create Date: 2026-05-14 19:15:58.801026

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1945bf0afe56'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('order_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_order_code'), 'orders', ['order_code'], unique=True)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.alter_column('inventory', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory', 'locked_stock',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('inventory_store_id_product_id_key'), 'inventory', type_='unique')
    op.create_index(op.f('ix_inventory_inventory_id'), 'inventory', ['inventory_id'], unique=False)
    op.drop_constraint(op.f('inventory_store_id_fkey'), 'inventory', type_='foreignkey')
    op.drop_constraint(op.f('inventory_product_id_fkey'), 'inventory', type_='foreignkey')
    op.create_foreign_key('inventory_product_id_fkey_new', 'inventory', 'products', ['product_id'], ['product_id'])
    op.create_foreign_key('inventory_store_id_fkey_new', 'inventory', 'stores', ['store_id'], ['store_id'])
    op.alter_column('inventory_locks', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="user_id::text::uuid")
    op.drop_index(op.f('idx_places_category_trgm'), table_name='places', postgresql_ops={'category': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_places_lat_lon'), table_name='places')
    op.drop_index(op.f('idx_places_name_trgm'), table_name='places', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(op.f('places_place_id_key'), 'places', type_='unique')
    op.create_index(op.f('ix_places_category'), 'places', ['category'], unique=False)
    op.create_index(op.f('ix_places_id'), 'places', ['id'], unique=False)
    op.create_index(op.f('ix_places_place_id'), 'places', ['place_id'], unique=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_products_embedding'), table_name='products', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_place_id'), 'reviews', ['place_id'], unique=False)
    op.alter_column('stores', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('stores', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=3, scale=1),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_index(op.f('idx_stores_lat_lon'), table_name='stores')
    op.drop_constraint(op.f('stores_place_id_key'), 'stores', type_='unique')
    op.create_index(op.f('ix_stores_store_id'), 'stores', ['store_id'], unique=False)
    op.alter_column('virtual_closets', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_virtual_closets_user_id'), 'virtual_closets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_closets_user_id'), table_name='virtual_closets')
    op.alter_column('virtual_closets', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_stores_store_id'), table_name='stores')
    op.create_unique_constraint(op.f('stores_place_id_key'), 'stores', ['place_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_stores_lat_lon'), 'stores', ['lat', 'lon'], unique=False)
    op.alter_column('stores', 'rating',
               existing_type=sa.Numeric(precision=3, scale=1),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('stores', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_reviews_place_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.create_index(op.f('idx_products_embedding'), 'products', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('products', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_places_place_id'), table_name='places')
    op.drop_index(op.f('ix_places_id'), table_name='places')
    op.drop_index(op.f('ix_places_category'), table_name='places')
    op.create_unique_constraint(op.f('places_place_id_key'), 'places', ['place_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_places_name_trgm'), 'places', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_places_lat_lon'), 'places', ['lat', 'lon'], unique=False)
    op.create_index(op.f('idx_places_category_trgm'), 'places', ['category'], unique=False, postgresql_ops={'category': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('inventory_locks', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using="user_id::text::integer")
    op.drop_constraint('inventory_product_id_fkey_new', 'inventory', type_='foreignkey')
    op.drop_constraint('inventory_store_id_fkey_new', 'inventory', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_product_id_fkey'), 'inventory', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('inventory_store_id_fkey'), 'inventory', 'stores', ['store_id'], ['store_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_inventory_inventory_id'), table_name='inventory')
    op.create_unique_constraint(op.f('inventory_store_id_product_id_key'), 'inventory', ['store_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('inventory', 'locked_stock',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('inventory', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_code'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
